categories = [
    "AI coding assistants",
    "DevOps tools",
    "Project management",
    "E-commerce platforms",
    "CRM software",
    "Marketing automation",
    "Data analytics",
    "Cybersecurity",
    "Cloud services",
    "Enterprise software",
    "Fintech",
    "Social media",
    "Content management",
    "Email marketing",
    "Search engine optimization",
    "FoodTech",
    "HealthTech",
    "Logistics",
    "Retail",
    "Travel",
    "Transportation",
    "Real estate",
    "Energy",
    "Media and entertainment",
    "Telecommunications",
    "Aerospace",
    "Automotive",
    "Biotechnology",
    "Chemicals",
    "Construction",
    "Defense",
    "Electronics",
    "Energy",
    "Financial services",
    "Food and beverage",
    "Healthcare",
    "Hospitality",
    "Insurance",
    "Manufacturing",
    "Materials",
    "Pharmaceuticals",
    "Public sector",
    "Retail",
    "Smart cities",
    "Sports",
    "Telecommunications",
    "Textiles",
    "Transportation",
    "Utilities",
    "Waste management",
    "Wellness and fitness",
    "Other"
]